server:
  port: 6666
spring:
  application:
    name: service-sleuth

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
