server:
  port: 8766

spring:
  application:
    name: kafka-coumue
  cloud:
    config:
      profile: dev
      label: master
      uri: http://localhost:8888/
#kakfa配置
  kafka:
    bootstrap-servers: localhost:9092  # 指定kafka 代理地址，可以多个
    consumer:
      group-id: user-log-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
