eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9999

spring:
  application:
    name: zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-hi
    api-b:
      path: /api-b/**
      serviceId: service-say
